[package]
name = "cmd"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "placement-center"
path = "src/placement-center/server.rs"
