cluster_name = "placement-test"
addr = "127.0.0.1"
node_id = 1                                         # 节点ID
grpc_port = 8871                                    # 节点监听的 GRPC 端口
http_port = 8971
nodes = { 1 = "127.0.0.1:1228" }
data_path = "/tmp/nezamq/local" # rocksdb 数据存储地址

[log]
log_config = "./config/log4rs.yaml"
log_path = "./logs"
