cluster_name = "placement-test"
addr = "127.0.0.1"
node_id = 1
grpc_port = 8871
http_port = 8971
nodes = { 1 = "127.0.0.1:1228" }
data_path = "/tmp/placement-center-geek/geek-local"

[log]
log_config = "./config/log4rs.yaml"
log_path = "./logs"
